@startuml
class Airport {
	+ accept(vehicle: FlyingTransport)
}


interface FlyingTransport <<Interface>> {
	+ fly(origin, destination passengers)
}


class Helicopter {
	+ fly(origin, destination passengers)
}


class AirPlane {
	+ fly(origin, destination passengers)
}


class DomesticatedGryphon {
	+ fly(origin, destination passengers)
}


Airport --> FlyingTransport
FlyingTransport <|.. Helicopter
FlyingTransport <|.. AirPlane
FlyingTransport <|.. DomesticatedGryphon


hide FlyingTransport circle


@enduml