@startuml
interface FourLegged {
	+ run(destination)
}


interface OxygenBreather {
	+ breath()
}


class Animal
CLASS Cat


Animal <|-- Cat
Cat .right.|> FourLegged
Cat .right.|> OxygenBreather: "           "
@enduml