@startuml


abstract class Animal {
	+ {abstract} void makeSound()
}


class Cat {
	+ makeSound()
}


class Dog {
	+ makeSound()
}


Animal <|-- Cat
Animal <|-- Dog
note bottom of Cat: makeSound(): std::cout << "Meow!" << std::endl; \nmakeSound2(): std::cout << "Meow!" << std::endl;
note bottom of Dog: makeSound(): std::cout << "Meow!" << std::endl;

@enduml