@startuml "聚合"

class Order {
	- taxCalculator
	- lineItems
	- country
	- state
	- city

	+ getOrderTotal()
}


class TaxCalculator {
	
	+ getTaxRate(country, state, product)
	- getUSTax(state)
	- getEUTax(country)
	- getChineseTax(product)
}


Order o.right.> TaxCalculator: "    聚合    "

@enduml