@startuml "组合优于继承"
class Transport << 运输  >> {
	- engine
	- driver

	+ deliver(destination, cargo)
}


class Engine << interface >> {
	+ move()
}


class Driver <<  interface  >> {
	+ navigate()
}



class CombustionEngine {}
class ElectricEngine {}
class Robot {}
class Human {}


Transport *--> Engine: "组合"
Transport o--> Driver: "聚合"

Engine <|.. CombustionEngine: "接口"
Engine <|.. ElectricEngine: "接口"

Driver <|.. Robot: "接口"
Driver <|.. Human: "接口"


@enduml