@startuml "关联: 实线+箭头"

class Professor {
    - JobTitle* job_title
	- std::vector<Student> student

	+ Professor(JobTitle * jt): job_title(jt) {}
    + addStudent(Student & stu)
}
class Student {}

Professor --> Student: 关联

note "备注: \n\
JobTitle* 表示的关系是一对一, \n\
std::vector<Student>表示的关系是一对多, \n\n\
\
job_title是由外部创建且在Professor初始化时传递进来的. \n\
std::vector<Student>是由addStudent方法维护的. \n\n\
\
Professor始终可以访问到job_title和student, \n\
Professor不负责初始化和销毁job_title和student, \n\
" as n1

note "\
The associated object (member) is otherwise unrelated to the object (class) \n\
类的关联对象(成员变量)与类本身是没有直接联系的.\
" as n2

Professor .up. n2
Professor .right. n1

@enduml