@startuml "继承"
class Animal {
	+name
	+sex
	+age
	+weight
	+color

	+breathe()
	+eat(food)
	+run(destination)
	+sleep(hours)
}

class Cat {
	-isNasty: bool

	+meow()
}


class Dog {
	-bestFriend: Human

	+bark()
}


Animal <|-- Cat: "继承"
Animal <|-- Dog: "继承"


note "备注: \n\
通过继承, 派生类(Cat和Dog)可以扩展基类. \n\
派生类分别扩展了一个成员变量和一个成员方法. \
" as n1


@enduml
